# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmp_allprobs <- function(lambda, nu, tol = 1e-6, take_log = FALSE, ymax = 1e100, normalize = TRUE) {
    .Call(`_COMPoissonReg_cmp_allprobs`, lambda, nu, tol, take_log, ymax, normalize)
}

dcmp_cpp <- function(x, lambda, nu, tol = 1e-6, take_log = FALSE, ymax = 1e100) {
    .Call(`_COMPoissonReg_dcmp_cpp`, x, lambda, nu, tol, take_log, ymax)
}

pcmp_cpp <- function(x, lambda, nu, tol = 1e-6, ymax = 1e100) {
    .Call(`_COMPoissonReg_pcmp_cpp`, x, lambda, nu, tol, ymax)
}

qcmp_cpp <- function(logq, lambda, nu, tol = 1e-6, ymax = 1e100) {
    .Call(`_COMPoissonReg_qcmp_cpp`, logq, lambda, nu, tol, ymax)
}

rcmp_cpp <- function(n, lambda, nu, tol = 1e-6, ymax = 1e100) {
    .Call(`_COMPoissonReg_rcmp_cpp`, n, lambda, nu, tol, ymax)
}

qdiscrete <- function(q, p, log_scale = FALSE) {
    .Call(`_COMPoissonReg_qdiscrete`, q, p, log_scale)
}

logsumprobs <- function(logprob, baseidx) {
    .Call(`_COMPoissonReg_logsumprobs`, logprob, baseidx)
}

logcumprobs <- function(logprob) {
    .Call(`_COMPoissonReg_logcumprobs`, logprob)
}

z_prodj <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodj`, lambda, nu, max)
}

z_prodj2 <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodj2`, lambda, nu, max)
}

z_prodjlogj <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodjlogj`, lambda, nu, max)
}

z_prodlogj <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodlogj`, lambda, nu, max)
}

z_prodlogj2 <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodlogj2`, lambda, nu, max)
}

z_trunc <- function(lambda, nu, tol = 1e-6, take_log = FALSE, ymax = 1e100) {
    .Call(`_COMPoissonReg_z_trunc`, lambda, nu, tol, take_log, ymax)
}

z_approx <- function(lambda, nu, take_log = FALSE) {
    .Call(`_COMPoissonReg_z_approx`, lambda, nu, take_log)
}

z_hybrid <- function(lambda, nu, take_log = FALSE, tol1 = 1e-2, tol2 = 1e-6) {
    .Call(`_COMPoissonReg_z_hybrid`, lambda, nu, take_log, tol1, tol2)
}

qzicmp_cpp <- function(logq, lambda, nu, p, tol = 1e-6) {
    .Call(`_COMPoissonReg_qzicmp_cpp`, logq, lambda, nu, p, tol)
}

