# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglik_cmp <- function(x, lambda, nu, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_loglik_cmp`, x, lambda, nu, hybrid_tol, truncate_tol, ymax)
}

d_cmp <- function(x, lambda, nu, take_log, normalize, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_d_cmp`, x, lambda, nu, take_log, normalize, hybrid_tol, truncate_tol, ymax)
}

p_cmp <- function(x, lambda, nu, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_p_cmp`, x, lambda, nu, hybrid_tol, truncate_tol, ymax)
}

q_cmp <- function(logq, lambda, nu, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_q_cmp`, logq, lambda, nu, hybrid_tol, truncate_tol, ymax)
}

r_cmp <- function(n, lambda, nu, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_r_cmp`, n, lambda, nu, hybrid_tol, truncate_tol, ymax)
}

q_discrete <- function(q, cp) {
    .Call(`_COMPoissonReg_q_discrete`, q, cp)
}

z_prodj <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodj`, lambda, nu, max)
}

z_prodj2 <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodj2`, lambda, nu, max)
}

z_prodjlogj <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodjlogj`, lambda, nu, max)
}

z_prodlogj <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodlogj`, lambda, nu, max)
}

z_prodlogj2 <- function(lambda, nu, max = 100L) {
    .Call(`_COMPoissonReg_z_prodlogj2`, lambda, nu, max)
}

z_trunc <- function(lambda, nu, tol, take_log, ymax) {
    .Call(`_COMPoissonReg_z_trunc`, lambda, nu, tol, take_log, ymax)
}

z_approx <- function(lambda, nu, take_log) {
    .Call(`_COMPoissonReg_z_approx`, lambda, nu, take_log)
}

z_hybrid <- function(lambda, nu, take_log, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_z_hybrid`, lambda, nu, take_log, hybrid_tol, truncate_tol, ymax)
}

y_trunc <- function(lambda, nu, tol, ymax) {
    .Call(`_COMPoissonReg_y_trunc`, lambda, nu, tol, ymax)
}

loglik_zicmp <- function(x, lambda, nu, p, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_loglik_zicmp`, x, lambda, nu, p, hybrid_tol, truncate_tol, ymax)
}

d_zicmp <- function(x, lambda, nu, p, take_log, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_d_zicmp`, x, lambda, nu, p, take_log, hybrid_tol, truncate_tol, ymax)
}

q_zicmp <- function(logq, lambda, nu, p, hybrid_tol, truncate_tol, ymax) {
    .Call(`_COMPoissonReg_q_zicmp`, logq, lambda, nu, p, hybrid_tol, truncate_tol, ymax)
}

