equitest <- function(object, ...) UseMethod("equitest")
leverage <- function(object, ...) UseMethod("leverage")
nu <- function(object, ...) UseMethod("nu")
sdev <- function (object, ...) UseMethod("sdev")
parametric_bootstrap <- function(object, ...) UseMethod("parametric_bootstrap")
